=== stephenfrancis/nucifera/src/schemas/template.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "DateBrevity": {
            "enum": [
                "long",
                "medium",
                "short",
                "very-short"
            ],
            "type": "string"
        },
        "DateEditField": {
            "properties": {
                "date_brevity": {
                    "$ref": "#/definitions/DateBrevity"
                },
                "date_fns_format": {
                    "type": "string"
                },
                "date_type": {
                    "$ref": "#/definitions/DateType"
                },
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "type": {
                    "enum": [
                        "date"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DateType": {
            "enum": [
                "date-only",
                "date-time",
                "time-only"
            ],
            "type": "string"
        },
        "ImageEditField": {
            "properties": {
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "type": {
                    "enum": [
                        "image"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "JSONEditField": {
            "properties": {
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "type": {
                    "enum": [
                        "json"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "NumberEditField": {
            "properties": {
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "max": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                },
                "type": {
                    "enum": [
                        "number"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "OptionsEditField": {
            "properties": {
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "options": {
                    "items": {
                        "type": "string"
                    },
                    "type": "array"
                },
                "type": {
                    "enum": [
                        "options"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Record<string,TemplateCell>": {
            "type": "object"
        },
        "RichtextEditField": {
            "properties": {
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "type": {
                    "enum": [
                        "richtext"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TemplateCell": {
            "anyOf": [
                {
                    "$ref": "#/definitions/TemplateCellArray"
                },
                {
                    "$ref": "#/definitions/TemplateCellContainer"
                },
                {
                    "$ref": "#/definitions/TemplateCellField"
                },
                {
                    "$ref": "#/definitions/TemplateCellMap"
                },
                {
                    "$ref": "#/definitions/TemplateCellText"
                }
            ]
        },
        "TemplateCellArray": {
            "properties": {
                "alignItems": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "border": {
                    "type": "string"
                },
                "cell": {
                    "$ref": "#/definitions/TemplateCell"
                },
                "color": {
                    "type": "string"
                },
                "flex": {
                    "type": "string"
                },
                "flexWrap": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/TemplateCellFormat"
                },
                "id": {
                    "type": "string"
                },
                "justifyContent": {
                    "type": "string"
                },
                "margin": {
                    "type": "string"
                },
                "padding": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TemplateCellContainer": {
            "properties": {
                "alignItems": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "border": {
                    "type": "string"
                },
                "cells": {
                    "items": {
                        "$ref": "#/definitions/TemplateCell"
                    },
                    "type": "array"
                },
                "color": {
                    "type": "string"
                },
                "flex": {
                    "type": "string"
                },
                "flexWrap": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/TemplateCellFormat"
                },
                "justifyContent": {
                    "type": "string"
                },
                "margin": {
                    "type": "string"
                },
                "padding": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TemplateCellField": {
            "properties": {
                "alignItems": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "border": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "field": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/DateEditField"
                        },
                        {
                            "$ref": "#/definitions/ImageEditField"
                        },
                        {
                            "$ref": "#/definitions/JSONEditField"
                        },
                        {
                            "$ref": "#/definitions/NumberEditField"
                        },
                        {
                            "$ref": "#/definitions/OptionsEditField"
                        },
                        {
                            "$ref": "#/definitions/RichtextEditField"
                        },
                        {
                            "$ref": "#/definitions/TextEditField"
                        }
                    ]
                },
                "flex": {
                    "type": "string"
                },
                "flexWrap": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/TemplateCellFormat"
                },
                "justifyContent": {
                    "type": "string"
                },
                "margin": {
                    "type": "string"
                },
                "padding": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TemplateCellFormat": {
            "enum": [
                "code",
                "h1",
                "h2",
                "h3",
                "p"
            ],
            "type": "string"
        },
        "TemplateCellMap": {
            "properties": {
                "alignItems": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "border": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "flex": {
                    "type": "string"
                },
                "flexWrap": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/TemplateCellFormat"
                },
                "id": {
                    "type": "string"
                },
                "justifyContent": {
                    "type": "string"
                },
                "map": {
                    "$ref": "#/definitions/Record<string,TemplateCell>"
                },
                "margin": {
                    "type": "string"
                },
                "padding": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TemplateCellText": {
            "properties": {
                "alignItems": {
                    "type": "string"
                },
                "backgroundColor": {
                    "type": "string"
                },
                "border": {
                    "type": "string"
                },
                "color": {
                    "type": "string"
                },
                "flex": {
                    "type": "string"
                },
                "flexWrap": {
                    "type": "string"
                },
                "format": {
                    "$ref": "#/definitions/TemplateCellFormat"
                },
                "justifyContent": {
                    "type": "string"
                },
                "margin": {
                    "type": "string"
                },
                "padding": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TextEditField": {
            "properties": {
                "hidden_for_edit": {
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "mandatory": {
                    "type": "boolean"
                },
                "maxLength": {
                    "type": "number"
                },
                "regex": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "text"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "properties": {
        "_id": {
            "type": "string"
        },
        "content": {
            "items": {
                "$ref": "#/definitions/TemplateCell"
            },
            "type": "array"
        },
        "description": {
            "type": "string"
        },
        "template": {
            "type": "string"
        }
    },
    "type": "object"
}

=== stephenfrancis/nucifera/src/predefined/builtin/main.json
{
  "_id": "main",
  "template": "builtin:template",
  "description": "Default template for a database's data documents",
  "content": [
    {
      "format": "h1",
      "field": {
        "type": "text",
        "id": "title"
      }
    },
    {
      "format": "p",
      "justifyContent": "space-between",
      "cells": [
        {
          "field": {
            "type": "date",
            "id": "created_at",
            "hidden_for_edit": true
          }
        },
        {
          "field": {
            "type": "text",
            "id": "created_by",
            "hidden_for_edit": true
          }
        }
      ]
    },
    {
      "format": "p",
      "field": {
        "type": "richtext",
        "id": "body"
      }
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/builtin/info.json
{
  "_id": "info",
  "template": "builtin:template",
  "description": "Standard template for a database's singleton info doc",
  "content": [
    {
      "format": "h1",
      "field": {
        "type": "text",
        "id": "_id"
      }
    },
    {
      "format": "h2",
      "text": "Templates"
    },
    {
      "format": "p",
      "id": "templates",
      "flexDirection": "column",
      "cell": {
        "field": {
          "id": "templates",
          "type": "text"
        }
      }
    },
    {
      "format": "h2",
      "text": "Views"
    },
    {
      "format": "p",
      "id": "views",
      "flexDirection": "column",
      "cell": {
        "field": {
          "id": "views",
          "type": "text"
        }
      }
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/builtin/view.json
{
  "_id": "view",
  "template": "builtin:template",
  "description": "Standard template for a database's views",
  "content": [
    {
      "format": "h1",
      "field": {
        "type": "text",
        "id": "_id"
      }
    },
    {
      "format": "p",
      "cells": [
        {
          "text": "Type"
        },
        {
          "field": {
            "type": "text",
            "id": "type"
          }
        }
      ]
    },
    {
      "format": "h2",
      "text": "Index"
    },
    {
      "format": "p",
      "id": "index",
      "cell": {
        "field": {
          "id": "index",
          "type": "text"
        }
      }
    },
    {
      "format": "h2",
      "text": "Selector"
    },
    {
      "format": "p",
      "id": "selector",
      "map": {
        "template": {
          "format": "p",
          "id": "template",
          "map": {
            "$regex": {
              "format": "p",
              "field": {
                "id": "$regex",
                "type": "text"
              }
            }
          }
        }
      }
    },
    {
      "format": "p",
      "cells": [
        {
          "text": "Show Doc Link"
        },
        {
          "field": {
            "type": "text",
            "id": "show_doc_link"
          }
        }
      ]
    },
    {
      "format": "h2",
      "text": "Columns"
    },
    {
      "format": "p",
      "field": {
        "id": "columns",
        "type": "json"
      }
    }
  ]
}
