=== stephenfrancis/nucifera/src/schemas/view.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "definitions": {
        "DateBrevity": {
            "enum": [
                "long",
                "medium",
                "short",
                "very-short"
            ],
            "type": "string"
        },
        "DateShowField": {
            "properties": {
                "date_brevity": {
                    "$ref": "#/definitions/DateBrevity"
                },
                "date_fns_format": {
                    "type": "string"
                },
                "date_type": {
                    "$ref": "#/definitions/DateType"
                },
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "date"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "DateType": {
            "enum": [
                "date-only",
                "date-time",
                "time-only"
            ],
            "type": "string"
        },
        "ImageShowField": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "image"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "JSONShowField": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "json"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "NumberShowField": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "number"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "OptionsShowField": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "options"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "RichtextShowField": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "richtext"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "TextShowField": {
            "properties": {
                "id": {
                    "type": "string"
                },
                "type": {
                    "enum": [
                        "text"
                    ],
                    "type": "string"
                }
            },
            "type": "object"
        },
        "ViewColumn": {
            "properties": {
                "field": {
                    "anyOf": [
                        {
                            "$ref": "#/definitions/DateShowField"
                        },
                        {
                            "$ref": "#/definitions/ImageShowField"
                        },
                        {
                            "$ref": "#/definitions/JSONShowField"
                        },
                        {
                            "$ref": "#/definitions/NumberShowField"
                        },
                        {
                            "$ref": "#/definitions/OptionsShowField"
                        },
                        {
                            "$ref": "#/definitions/RichtextShowField"
                        },
                        {
                            "$ref": "#/definitions/TextShowField"
                        }
                    ]
                },
                "initialWidth": {
                    "$ref": "#/definitions/Width"
                },
                "label": {
                    "type": "string"
                }
            },
            "type": "object"
        },
        "Width": {
            "enum": [
                "free",
                "l",
                "m",
                "s",
                "xl",
                "xs"
            ],
            "type": "string"
        }
    },
    "properties": {
        "_id": {
            "type": "string"
        },
        "columns": {
            "items": {
                "$ref": "#/definitions/ViewColumn"
            },
            "type": "array"
        },
        "description": {
            "type": "string"
        },
        "index": {},
        "new_doc_link": {
            "type": "string"
        },
        "selector": {},
        "show_doc_link": {
            "type": "string"
        },
        "sort": {
            "items": {
                "type": "string"
            },
            "type": "array"
        },
        "template": {
            "type": "string"
        },
        "type": {
            "enum": [
                "list"
            ],
            "type": "string"
        }
    },
    "type": "object"
}

=== stephenfrancis/nucifera/src/predefined/builtin/design.json
{
  "_id": "design",
  "template": "builtin:view",
  "description": "View of all design documents for a database - views and templates",
  "type": "list",
  "index": ["template"],
  "selector": {
    "template": {
      "$regex": "^builtin:"
    }
  },
  "columns": [
    {
      "id": "_id",
      "label": "Title",
      "type": "text"
    },
    {
      "id": "type",
      "label": "Type",
      "type": "text"
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/trees/docs.json
{
  "_id": "docs",
  "template": "builtin:view",
  "type": "list",
  "index": ["template"],
  "selector": {
    "template": {
      "$regex": "^(?!builtin:.*$).*"
    }
  },
  "columns": [
    {
      "id": "name",
      "label": "Name",
      "type": "text"
    },
    {
      "id": "created_at",
      "label": "Created At",
      "type": "date"
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/builtin/docs.json
{
  "_id": "docs",
  "template": "builtin:view",
  "description": "Default view of a database's data documents",
  "type": "list",
  "index": ["template"],
  "selector": {
    "template": {
      "$regex": "^(?!builtin:.*$).*"
    }
  },
  "columns": [
    {
      "field": {
        "id": "title",
        "type": "text"
      },
      "label": "Title"
    },
    {
      "field": {
        "id": "created_at",
        "type": "date"
      },
      "label": "Created At"
    },
    {
      "field": {
        "id": "created_by",
        "type": "text"
      },
      "label": "Created By"
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/trees/shrubs.json
{
  "_id": "shrubs",
  "template": "builtin:view",
  "type": "list",
  "index": ["template"],
  "selector": {
    "template": {
      "$eq": "shrub"
    }
  },
  "columns": [
    {
      "field": {
        "id": "name",
        "type": "text"
      },
      "label": "Name"
    },
    {
      "field": {
        "id": "created_at",
        "type": "date"
      },
      "label": "Created At"
    },
    {
      "field": {
        "id": "max_height",
        "type": "number"
      },
      "label": "Max Height"
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/databases/docs.json
{
  "_id": "docs",
  "template": "builtin:view",
  "type": "list",
  "columns": [
    {
      "id": "_id",
      "label": "Id",
      "type": "text"
    },
    {
      "id": "label",
      "label": "Label",
      "type": "text"
    },
    {
      "id": "remote_url",
      "label": "Remote URL",
      "type": "text"
    }
  ]
}

=== stephenfrancis/nucifera/src/predefined/trees/deciduouses.json
{
  "_id": "deciduouses",
  "template": "builtin:view",
  "type": "list",
  "index": ["template"],
  "selector": {
    "template": {
      "$eq": "deciduous"
    }
  },
  "columns": [
    {
      "field": {
        "id": "name",
        "type": "text"
      },
      "label": "Name"
    },
    {
      "field": {
        "id": "created_at",
        "type": "date"
      },
      "label": "Created At"
    },
    {
      "field": {
        "id": "when_leaves_fall",
        "type": "text"
      },
      "label": "When Leaves Fall"
    }
  ]
}
